Allow log destinations to be configured
mission-apprentissage/tables-correspondances pull request #123
Opened 2021-03-24 10:35 UTC by bguerout

Permet de définir la liste des destinations dans lesquelles on veut mettre les logs.

Exemple :
`TABLES_CORRESPONDANCES_LOG_DESTINATIONS=mongodb,stdout,slack`

Le but premier était de pouvoir désactiver la sauvegarde des logs dans mongodb pour les scripts:

`TABLES_CORRESPONDANCES_LOG_DESTINATIONS=stdout`

2021-03-24 10:37 UTC, Gethi requested changes
Attention gros impact sur le sdk. Il faudrait tester

2021-03-24 10:41 UTC, Gethi commented on server/src/common/mongodb.js
> -
pas trop chaud pour les enlever

2021-03-24 10:41 UTC, Gethi commented on server/config/custom-environment-variables.json
> +    "destinations": "TABLES_CORRESPONDANCES_LOG_DESTINATIONS"
impact le sdk il me semble

2021-03-24 10:41 UTC, Gethi commented on server/src/common/logger.js
>  module.exports = bunyan.createLogger({
en utilisation SDK, aujourd’hui, on ne peut utiliser que en "type" Json.

2021-03-24 10:41 UTC, Gethi commented on server/config/custom-environment-variables.json
> +    "destinations": "TABLES_CORRESPONDANCES_LOG_DESTINATIONS"
car la on ne passe plus le type

2021-03-24 10:45 UTC, bguerout commented on server/src/common/mongodb.js
> -
L'event sur les erreurs est en double.
Pour les autres il faudrait au moins changer le wording 'Error...' car ce n'est pas une erreur

2021-03-24 10:46 UTC, bguerout commented on server/config/custom-environment-variables.json
> +    "destinations": "TABLES_CORRESPONDANCES_LOG_DESTINATIONS"
IL faudrait que je vois comment marche le sdk.
Tu as un lien sur lequel je pourrais voir comment ca fonctionne ?

2021-03-24 10:49 UTC, bguerout commented on server/config/custom-environment-variables.json
> +    "destinations": "TABLES_CORRESPONDANCES_LOG_DESTINATIONS"
Ah ok il est la https://github.com/mission-apprentissage/tables-correspondances/tree/sdk/server/src/sdk

2021-04-12 07:05 UTC, ericplaquevent commented on server/src/common/logger.js
>  module.exports = bunyan.createLogger({
stdout ça passe :)

2021-09-21 15:40 UTC, closed without merging